### ISSUE TITLE
Crash with the lastest version

### ISSUE THREAD

**Issue by sdv3** [LuziferSenpai/Rich-Text-Helper#2]
The latest version crashed after I entered a number into a FactoryPlanner window

Error while running event Rich_Text_Helper::on_gui_text_changed (ID 2)
LuaGuiElement API call when LuaGuiElement was invalid.
stack traceback:
	__Rich_Text_Helper__/control.lua:486: in function <__Rich_Text_Helper__/control.lua:480>
stack traceback:
	[C]: in function '__index'
	__Rich_Text_Helper__/control.lua:486: in function <__Rich_Text_Helper__/control.lua:480

**Comment by LuziferSenpai** [comment]
Sry, my Fail. Fixed in Version 0.1.1
